image:
  file: Dockerfile
checkoutLocation: chromium/src/
tasks:
  - init: >
      gclient runhooks &&
      gn gen out/Default --args="enable_nacl=false is_component_build=true use_jumbo_build=true symbol_level=1"
